import { PrismaClient } from "@prisma/client";

const db = new PrismaClient();

const categories = [
  "Electronics",
  "Clothing",
  "Books",
  "Home & Kitchen",
  "Beauty & Personal Care",
  "Toys & Games",
  "Sports & Outdoors",
  "Health & Household",
  "Automotive",
  "Tools & Home Improvement",
  "Grocery & Gourmet Food",
  "Pet Supplies",
  "Baby",
  "Office Products",
  "Industrial & Scientific",
  "Arts, Crafts & Sewing",
  "Movies & TV",
  "Music",
  "Video Games",
  "Computers",
  "Cell Phones & Accessories",
  "Camera & Photo",
  "Software",
  "Kindle Store",
  "Magazine Subscriptions",
  "Grocery",
  "Specialty Foods",
  "Alcoholic Beverages",
  "Beverages",
  "Meat & Seafood",
  "Fresh Flowers & Live Indoor Plants",
  "Restaurants",
  "Gift Cards",
  "Industrial & Scientific",
  "Commercial Lighting",
  "Janitorial & Sanitation Supplies",
  "Test, Measure & Inspect",
  "Occupational Health & Safety Products",
  "Science Education",
  "Lab & Scientific Products",
  "Janitorial & Sanitation Supplies",
  "Commercial Door Products",
  "Material Handling Products",
  "Industrial Hardware",
  "Power & Hand Tools",
  "Hydraulics, Pneumatics & Plumbing",
  "Industrial Electrical",
  "Industrial Power & Hand Tools",
  "Commercial Lighting",
  "Commercial Door Products",
  "Cutting Tools",
  "Hydraulics, Pneumatics & Plumbing",
  "Industrial Motors",
  "Material Handling Products",
  "Pneumatic Equipment",
  "Power Transmission Products",
  "Industrial Electrical",
  "Abrasive & Finishing Products",
  "Industrial Hardware",
  "Lubricants & Oils",
  "Pumps & Accessories",
  "Rope, Cord & Webbing",
  "Safety & Security",
  "Scaffolding",
  "Shims & Shim Stock",
  "Tapes, Adhesives & Sealants",
  "Welding & Soldering",
  "Fasteners",
  "Food Service Equipment & Supplies",
  "Furniture",
  "Home Décor",
  "Artwork",
  "Bedding",
  "Bath",
  "Event & Party Supplies",
  "Heating, Cooling & Air Quality",
  "Iron & Steamers",
  "Vacuums & Floor Care",
  "Storage & Organization",
  "Cleaning Supplies",
  "Laundry",
  "Pet Supplies",
  "Garden & Outdoor",
  "Patio Furniture & Accessories",
  "Outdoor Décor",
  "Grills & Outdoor Cooking",
  "Pools, Hot Tubs & Supplies",
  "Generators & Portable Power",
  "Outdoor Heating & Cooling",
  "Outdoor Storage",
  "Outdoor Lighting",
  "Plants, Seeds & Bulbs",
  "Lawn Care",
  "Gardening & Lawn Care",
  "Fertilizers & Plant Food",
  "Garden Décor",
  "Pest Control",
  "Snow Removal",
  "Landscaping",
  "Watering Equipment",
];

const initializeCategories = async () => {
  try {
    const uniqueCategories = Array.from(
      new Set(categories.map((cat) => ({ name: cat }))),
    );

    await db.category.createMany({
      data: uniqueCategories,
      skipDuplicates: true,
    });

    console.log("Categories initialization completed successfully.");
  } catch (error) {
    console.error("Error initializing categories:", error);
  }
};

await initializeCategories();
